# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mybooks.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mybooks.proto',
  package='books',
  syntax='proto3',
  serialized_pb=_b('\n\rmybooks.proto\x12\x05\x62ooks\"\x07\n\x05\x45mpty\"1\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"&\n\x08\x42ookList\x12\x1a\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0b.books.Book\"%\n\x12\x42ookStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1b\n\rBookIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xab\x02\n\x0b\x42ookService\x12\'\n\x04List\x12\x0c.books.Empty\x1a\x0f.books.BookList\"\x00\x12*\n\x03Get\x12\x14.books.BookIdRequest\x1a\x0b.books.Book\"\x00\x12\x30\n\x04Post\x12\x0b.books.Book\x1a\x19.books.BookStatusResponse\"\x00\x12/\n\x03Put\x12\x0b.books.Book\x1a\x19.books.BookStatusResponse\"\x00\x12;\n\x06\x44\x65lete\x12\x14.books.BookIdRequest\x1a\x19.books.BookStatusResponse\"\x00\x12\'\n\x05Watch\x12\x0b.books.Book\x1a\x0b.books.Book\"\x00(\x01\x30\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='books.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=31,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='books.Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='books.Book.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='books.Book.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='books.Book.author', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=82,
)


_BOOKLIST = _descriptor.Descriptor(
  name='BookList',
  full_name='books.BookList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='books', full_name='books.BookList.books', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=122,
)


_BOOKSTATUSRESPONSE = _descriptor.Descriptor(
  name='BookStatusResponse',
  full_name='books.BookStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='books.BookStatusResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=161,
)


_BOOKIDREQUEST = _descriptor.Descriptor(
  name='BookIdRequest',
  full_name='books.BookIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='books.BookIdRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=190,
)

_BOOKLIST.fields_by_name['books'].message_type = _BOOK
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
DESCRIPTOR.message_types_by_name['BookList'] = _BOOKLIST
DESCRIPTOR.message_types_by_name['BookStatusResponse'] = _BOOKSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['BookIdRequest'] = _BOOKIDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'mybooks_pb2'
  # @@protoc_insertion_point(class_scope:books.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), dict(
  DESCRIPTOR = _BOOK,
  __module__ = 'mybooks_pb2'
  # @@protoc_insertion_point(class_scope:books.Book)
  ))
_sym_db.RegisterMessage(Book)

BookList = _reflection.GeneratedProtocolMessageType('BookList', (_message.Message,), dict(
  DESCRIPTOR = _BOOKLIST,
  __module__ = 'mybooks_pb2'
  # @@protoc_insertion_point(class_scope:books.BookList)
  ))
_sym_db.RegisterMessage(BookList)

BookStatusResponse = _reflection.GeneratedProtocolMessageType('BookStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _BOOKSTATUSRESPONSE,
  __module__ = 'mybooks_pb2'
  # @@protoc_insertion_point(class_scope:books.BookStatusResponse)
  ))
_sym_db.RegisterMessage(BookStatusResponse)

BookIdRequest = _reflection.GeneratedProtocolMessageType('BookIdRequest', (_message.Message,), dict(
  DESCRIPTOR = _BOOKIDREQUEST,
  __module__ = 'mybooks_pb2'
  # @@protoc_insertion_point(class_scope:books.BookIdRequest)
  ))
_sym_db.RegisterMessage(BookIdRequest)



_BOOKSERVICE = _descriptor.ServiceDescriptor(
  name='BookService',
  full_name='books.BookService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=193,
  serialized_end=492,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='books.BookService.List',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_BOOKLIST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='books.BookService.Get',
    index=1,
    containing_service=None,
    input_type=_BOOKIDREQUEST,
    output_type=_BOOK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Post',
    full_name='books.BookService.Post',
    index=2,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOKSTATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Put',
    full_name='books.BookService.Put',
    index=3,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOKSTATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='books.BookService.Delete',
    index=4,
    containing_service=None,
    input_type=_BOOKIDREQUEST,
    output_type=_BOOKSTATUSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Watch',
    full_name='books.BookService.Watch',
    index=5,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKSERVICE)

DESCRIPTOR.services_by_name['BookService'] = _BOOKSERVICE

# @@protoc_insertion_point(module_scope)
